# Generated by Django 5.0.6 on 2026-07-19 12:59

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BettingPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('highlight_note', models.CharField(blank=True, max_length=150)),
                ('website_url', models.URLField()),
                ('rank_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['rank_order'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage off'), ('fixed', 'Fixed amount off (UGX)')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage (0-100) if type is percentage, otherwise UGX amount', max_digits=10)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
                ('active_from', models.DateTimeField()),
                ('active_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicable_plans', models.ManyToManyField(blank=True, help_text='Leave empty to apply to all plans', to='accounts.subscriptionplan')),
            ],
        ),
        migrations.CreateModel(
            name='PesapalTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_reference', models.CharField(max_length=64, unique=True)),
                ('order_tracking_id', models.CharField(blank=True, max_length=128)),
                ('amount_ugx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=12)),
                ('status_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesapal_transactions', to='accounts.user')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.promocode')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price_ugx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price_ugx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionplan')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='recommendations.promocode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_redemptions', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_type', models.CharField(choices=[('home_win', 'Home win'), ('away_win', 'Away win'), ('draw', 'Draw'), ('corners', 'Corners'), ('btts', 'Both teams to score'), ('over_under', 'Over/under goals')], max_length=20)),
                ('risk_tier', models.CharField(choices=[('low', 'Low risk'), ('medium', 'Medium risk'), ('high', 'High risk')], max_length=10)),
                ('confidence_score', models.FloatField(help_text="Model's confidence in this outcome, 0-100", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('suggested_odds_min', models.FloatField()),
                ('suggested_odds_max', models.FloatField()),
                ('head_to_head_weight', models.FloatField(default=0)),
                ('recent_form_weight', models.FloatField(default=0)),
                ('squad_news_weight', models.FloatField(default=0)),
                ('reasoning_summary', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('hit', 'Hit'), ('missed', 'Missed')], default='pending', max_length=10)),
                ('outcome_evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='matches.match')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SeasonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('total_budget_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_earnings_ugx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('risk_appetite', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_plans', to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField()),
                ('week_starts_on', models.DateField()),
                ('target_stake_ugx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('target_odds_to_chase', models.FloatField()),
                ('actual_invested_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('actual_earned_ugx', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('season_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_targets', to='recommendations.seasonplan')),
            ],
            options={
                'ordering': ['week_number'],
            },
        ),
        migrations.CreateModel(
            name='UserBetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stake_ugx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('odds_taken', models.FloatField()),
                ('followed_recommendation', models.BooleanField(default=True)),
                ('result', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10)),
                ('payout_ugx', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('recommendation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bet_logs', to='recommendations.recommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bet_logs', to='accounts.user')),
                ('week', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recommendations.weeklytarget')),
            ],
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['match', 'bet_type'], name='recommendat_match_i_f4b81f_idx'),
        ),
        migrations.AddIndex(
            model_name='seasonplan',
            index=models.Index(fields=['user', 'is_active'], name='recommendat_user_id_f07481_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='weeklytarget',
            unique_together={('season_plan', 'week_number')},
        ),
    ]
